before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FaAYERUrs4jEq/fpfuyrXy5fqcHLos4HW+J7sQldpwyu8q+Zgj6QIYpyyYzGQHZTCY/Z1WOJcbB8bVxjHA9aUBG+Thd3fHZqU/jTj28p/loDmTmTuD+fcg5+xE52A8IkAT8h7XiGn+dhMm+V2UWCu5X8IOAprfszW1jBNNwYAhmxvycfoAygrb53Be3XK5Q0IDZ8z5Y67bLrwezP0L0VEQsWJpToErPu9t+MzY4+VC6xTj1r/+2A+ajVFNASxUc2145Pv9t6HFM6wQdqu5UEnhD5I8Tb8J4wUZQBER6MGZJWxDg3BYBLEhbzdvhXTb2upmE0L0nMiXrFijAHSQYlivCkkz5hvy3elGnYvaVThEY1U31kuj7yPbPXRJq9EIYfcsc3WUC8cBupG2SabTYvOkZx0fTQrhQvyMHOgaohtYyHveeG9dPvItYJ1hWXtzFjRLtJb2IerVysqxgMBWd4+f9NsV37+t1hFWslb2QrqQNgZCC6A5Xp5fxFBNXi5fXac3cQtymKVNzfzY0zntfouw1H9dUpSyTHgUFJprplM79XucezHKzbkijfHqLCMnG9BfJ4zIX3rNq4hPlUCkLF/GbT1L6PblyAhhib+rV6KIzYCJh7X6+UG5cGcFyC9MDZQ2bsBDCPxeuV5EflxM9yFlj/+0DYrDA2HOHbDt7sWJc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
